---
- name: install mysql
  yum: name={{ item }} state=installed
  with_items:
   - mariadb
   - mariadb-server
   - MySQL-python

- name: install MySQL-python in loacl
  yum: name={{ item }} state=installed
  with_items:
   - mariadb
   - mariadb-server
   - MySQL-python

- name: change master mysql config
  delegate_to: "{{ groups['master_dbserver'][0] }}"
  run_once: true
  template: src=master.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: change slave mysql config
  delegate_to: "{{ groups['slave_dbserver'][0] }}"
  run_once: true
  template: src=slave.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: start mysql service
  service: name=mariadb state=started enabled=yes

- name: change root password
  mysql_user: name=root password={{ root_password }} sql_log_bin=no
  ignore_errors: true

- name: create zabbix db user
  mysql_user: name={{ user }} password={{ password }} priv=*.*:ALL host='%' state=present login_user=root login_password={{ root_password }} sql_log_bin=no

- name: get master status
  mysql_replication:
    mode: getmaster
    login_user: root
    login_password: "{{ root_password }}"
  delegate_to: "{{ groups['master_dbserver'][0] }}"
  run_once: true
  register: master

- name: get slave status
  mysql_replication:
    mode: getslave
    login_user: root
    login_password: "{{ root_password }}"
  delegate_to: "{{ groups['slave_dbserver'][0] }}"
  run_once: true
  register: slave

- name: stop slave
  delegate_to: "{{ groups['slave_dbserver'][0] }}"
  run_once: true
  mysql_replication:
    login_user: root
    login_password: "{{ root_password }}"
    mode: stopslave

- name: add replication
  delegate_to: "{{ groups['slave_dbserver'][0] }}"
  run_once: true
  mysql_replication:
    mode: changemaster
    master_host: "{{ groups['master_dbserver'][0] }}"
    master_user: "{{ master_user }}"
    master_password: "{{ master_password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
    login_user: root
    login_password: "{{ root_password }}"

- name: start slave
  delegate_to: "{{ groups['slave_dbserver'][0] }}"
  run_once: true
  mysql_replication:
    mode: startslave
    login_user: root
    login_password: "{{ root_password }}"
