---
- name: disable selinux
  selinux:
    state: disabled

# - name: add repository
#   yum_repository:
#     name: "{{ repo_name }}"
#     description: Ali YUM repo
#     baseurl: "{{ ali_repo_baseurl }}"

- name: copy yum repo
  copy:
    src: Centos-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
  notify:
    - clean yum cache
    - generate yum cache
